spring:
  application:
    name: cs-api-entrypoint
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true

services:
  uri:
    users-service: ${USERS_SERVICE_URI}
    events-service: ${EVENTS_SERVICE_URI}
    mail-service: ${MAIL_SERVICE_URI}
    file-service: ${FILE_SERVICE_URI}
  frontend:
    local: ${LOCAL_HOST}
    production: ${PRODUCTION_HOST}
    productionPattern: ${PRODUCTION_HOST_PATTERN}

server:
  port: 8080