spring:
  application:
    name: cs-api-entrypoint

services:
  uri:
    users-service: ${USERS_SERVICE_URI}
    events-service: ${EVENTS_SERVICE_URI}
    mail-service: ${MAIL_SERVICE_URI}
    file-service: ${FILE_SERVICE_URI}
  frontend:
    local: ${LOCAL_HOST}
    production: ${PRODUCTION_HOST}

server:
  port: 8080