spring:
  application:
    name: cs-api-entrypoint

services:
  uri:
    users-service: ${USERS_SERVICE_URI}
    events-service: ${EVENTS_SERVICE_URI}
    mail-service: ${MAIL_SERVICE_URI}

server:
  port: 8080